// Durable identity for library sources and chunks.
//
// Chrome's tabId is NOT a durable document identity: Chrome reuses tab IDs after a tab closes,
// and navigating an existing tab keeps the same tabId while the content underneath changes
// completely (see README "Known limitations" in the pre-Qdrant version, which already called
// this out as a bug). Everything persisted in Qdrant is keyed off a canonical URL instead;
// tabId only ever identifies a *working-set* pointer (background.js / popup.js), never a
// document in the library.

const DEFAULT_TRACKING_PARAMS = [
  "utm_source",
  "utm_medium",
  "utm_campaign",
  "utm_term",
  "utm_content",
  "gclid",
  "fbclid",
  "mc_cid",
  "mc_eid",
  "ref",
  "ref_src",
  "igshid",
];

// Canonicalization policy (documented, not hidden, because "canonical URL" is otherwise a
// hand-wave):
//   1. Parse with the URL API; reject non-http(s) schemes (chrome://, file://, data:, etc. are
//      never indexable sources).
//   2. Lowercase scheme and host. Path/query casing is preserved (some servers are case-sensitive).
//   3. Strip default ports (":80" on http, ":443" on https).
//   4. Drop the fragment (#...) -- it never changes server-returned content.
//   5. Drop a fixed list of known tracking query params (see DEFAULT_TRACKING_PARAMS). All other
//      query params are kept and their relative order preserved, because query params legitimately
//      change page content (e.g. ?version=2, ?tab=changelog).
//   6. Strip a single trailing slash from the path, unless the path is just "/".
// This is a heuristic, not a perfect canonicalizer -- two URLs that a site treats as identical
// but that differ in some other way (case-insensitive path, different query param order that the
// server treats as equivalent) will still be treated as different sources here. That's an
// explicit, documented limitation, not a silent one.
export function canonicalizeUrl(rawUrl) {
  let url;
  try {
    url = new URL(rawUrl);
  } catch {
    throw new Error(`Not a valid absolute URL: ${rawUrl}`);
  }
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    throw new Error(`Unsupported scheme for a library source: ${url.protocol}`);
  }

  const scheme = url.protocol.toLowerCase();
  const host = url.hostname.toLowerCase();
  const isDefaultPort =
    (scheme === "http:" && (url.port === "" || url.port === "80")) ||
    (scheme === "https:" && (url.port === "" || url.port === "443"));
  const port = isDefaultPort ? "" : `:${url.port}`;

  const params = new URLSearchParams(url.search);
  for (const key of DEFAULT_TRACKING_PARAMS) params.delete(key);
  const query = params.toString();

  let path = url.pathname;
  if (path.length > 1 && path.endsWith("/")) path = path.slice(0, -1);
  if (path === "") path = "/";

  return `${scheme}//${host}${port}${path}${query ? `?${query}` : ""}`;
}

export function domainOf(canonicalUrl) {
  try {
    return new URL(canonicalUrl).hostname.toLowerCase();
  } catch {
    return "unknown";
  }
}

async function sha256Hex(text) {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// A deterministic source key is the thing everything else (Qdrant point IDs, working-set
// mapping, "is this the same source as before" checks) is keyed on. It is a hash of the
// canonical URL, never the raw URL/title themselves -- per explicit instruction, no raw URL or
// title goes into an ID. The canonical URL string itself is still stored in the payload (that's
// fine and necessary for citations); only the *identifier* is hashed.
export async function sourceKeyFor(canonicalUrl) {
  return sha256Hex(`ask-my-tabs:source:v1:${canonicalUrl}`);
}

// Qdrant accepts unsigned integer or UUID-shaped string point IDs -- it does not implement or
// verify RFC 4122 UUID semantics server-side, so a deterministic hash formatted into UUID dashes
// is accepted as a valid point ID and is stable across re-indexing runs (verified against a live
// v1.11.0 container: upserting the same formatted ID twice with different payloads overwrites
// rather than duplicates, which is exactly the idempotency this project needs).
function hashToUuidV4Shape(hashHex) {
  // Take 32 hex chars, force the version/variant nibbles so the string is UUID-shaped (v4-looking)
  // even though it's not generated by an RNG -- Qdrant just needs the shape, and a fixed shape
  // makes it obvious in tooling/logs that these are derived, not random, IDs.
  const h = hashHex.slice(0, 32).padEnd(32, "0").split("");
  h[12] = "4";
  const variantNibble = "89ab"[parseInt(h[16], 16) % 4];
  h[16] = variantNibble;
  const s = h.join("");
  return `${s.slice(0, 8)}-${s.slice(8, 12)}-${s.slice(12, 16)}-${s.slice(16, 20)}-${s.slice(20, 32)}`;
}

// One deterministic point ID per (source, snapshot content hash, chunk index). Re-indexing
// unchanged content re-derives the exact same ID, so re-upserting is a true no-op at the point
// level, not just skipped at the indexTab() call level -- belt-and-suspenders against any caller
// that forgets the content-hash short-circuit.
export async function chunkPointId(sourceKey, contentHash, chunkIndex) {
  const hex = await sha256Hex(`ask-my-tabs:point:v1:${sourceKey}:${contentHash}:${chunkIndex}`);
  return hashToUuidV4Shape(hex);
}
